models/Post.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "post".
 *
 * @property int $id
 * @property string $title
 * @property string|null $lead
 * @property string|null $text
 * @property int|null $created_at
 */
class Post extends \yii\db\ActiveRecord
{

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => false,
                'value' => time(),
            ],
        ];
    }


    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'post';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title'], 'required'],
            [['text'], 'string'],
            [['created_at'], 'integer'],
            [['title'], 'string', 'max' => 50],
            [['lead'], 'string', 'max' => 150],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'lead' => 'Lead',
            'text' => 'Text',
            'created_at' => 'Created At',
        ];
    }

    public function actionView($id) {
        $post = Post::find()->where(['id' => $id])->one();

        if ($post) {
            return $this->render('view', ['model' => $post]);
        }
        throw new \yii\web\NotFoundHttpException("Пост не найден");
    }
}

controllers/PostController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;

use app\models\Post;
use app\models\PostSearch;
use app\models\PostFrontendSearch;

class PostController extends Controller {

    // список всех постов блога
    public function actionIndex()
    {
        $searchModel = new PostFrontendSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel
        ]);
    }


    // отдельный пост
    public function actionView($id) {
        $post = Post::find()->where(['id' => $id])->one();

        if ($post) {
            return $this->render('view', ['model' => $post]);
        }
        throw new \yii\web\NotFoundHttpException("Пост не найден");
    }



}

views/post/_listItem.php
<?php
    use yii\helpers\Html;

    $this->title = "Список постов";
?>

<div class="row">
    <h3>
        <?= Html::a($model->title, ['post/view', 'id' => $model->id]) ?>
    </h3>
    <p><?= $model->lead ?></p>
</div>

views/post/index.php
<?php
    use yii\widgets\ListView;

    use yii\helpers\Html;
    use yii\widgets\ActiveForm;

    $this->title = 'Все посты';

    $searchString = \yii\helpers\ArrayHelper::getValue(Yii::$app->request->queryParams, "PostFrontendSearch.text");
    if ($searchString) {
        $this->title = 'Результаты поиска';
    }
?>

<div class="row">
    <?php $form = ActiveForm::begin([
        'method' => 'get',
    ]); ?>
    <div class="col-sm-12 col-md-1">
        Поиск
    </div>

    <div class="col-sm-12 col-md-3">
        <?= $form->field($searchModel, 'text')
            ->textInput(['placeholder' => 'Введите строку для поиска'])
            ->label(false);
        ?>
    </div>

    <div class="col-sm-12 col-md-1">
        <?= Html::submitButton('Искать', ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>

<?php if ($searchString): ?>
    <h1>Вы искали: "<?= Html::encode($searchString); ?>"</h1>
<?php else: ?>
    <h1>Все посты</h1>
<?php endif; ?>

<section>
    <?php
        echo ListView::widget([
                'dataProvider' => $dataProvider,
                'itemView' => '_listItem',
        ])
    ?>
</section>

views/post/view.php
<?php
    $this->title = $model->title;
?>

<acrticle>
    <p><?= date('d.m.Y', $model->created_at) ?></p>
    <h1><?= $model->title ?></h1>
    <p><?= $model->text ?></p>
</acrticle>